# Word Representations

## *"I know words. I have the best words!"*
    - Noam Chomsky

# Dense Distributed Representations

In [65]:
import pandas as pd
import numpy as np
df = pd.read_csv('../data/reviews.full.tsv', sep='\t', nrows=1000)
documents = df.text.tolist()


## Exercise 1
Use `spacy` to restrict the words in the reviews to *content words*, i.e., nouns, verbs, and adjectives. Transform the words to lower case and add the POS with an underderscore. E.g.:

`love_VERB old-fashioneds_NOUN`

This also allows us to distinguish between homographs, i.e., words that are written the same, but belong to different word classes, e.g., *love* in "I **love** old-fashioneds" vs. "He felt so sick, it must have been **love**".


Make sure to exclude sentences that contain none of the above.

Write the resulting corpus to a variable called `word_corpus`.

In [56]:
import spacy
import nltk
from nltk.corpus import stopwords

nlp = spacy.load('en_core_web_sm', disable=['parser', 'ner'])
stopwords_ = set(stopwords.words('english'))

tokensss=[]
for sentence in documents [:100]:
    for token in nlp(sentence):
        if len(token) > 2 and token not in stopwords_:
            tokens = token.text.lower()
            pos = token.pos_
            tokensss.append(tokens + '_' + pos)

In [57]:
from gensim.models import Word2Vec
from gensim.models.word2vec import FAST_VERSION

corpus = [token.split() for token in tokensss]

word_corpus = Word2Vec(size = 100, window = 5, hs = 0, sample = 0.000001, negative = 5, min_count = 2, iter = 5000, seed=1)
a = word_corpus.build_vocab(corpus)
b = word_corpus.train(corpus, total_examples = word_corpus.corpus_count, epochs = word_corpus.epochs)

Rerun the `Word2vec` model from above on the new data set and test the words out

In [58]:
w_v = word_corpus.wv['have_VERB']

m_s = word_corpus.wv.most_similar(['have_VERB'])

w_v
#word_corpus.wv.most_similar(positive=['', ''], negative=[''], topn=3)

array([-3.4191443e-03,  4.1637928e-03,  4.3452671e-03,  1.1700979e-03,
        1.3707120e-03,  2.7096933e-03, -3.4324133e-03,  3.4854752e-06,
        2.1465884e-03, -2.4696887e-03,  3.7737912e-03, -1.0300397e-03,
       -1.2391248e-03, -4.3925722e-03, -3.4723759e-03,  3.6126757e-03,
        1.6699817e-04, -3.2605417e-04, -2.2566060e-03,  4.3591470e-03,
        1.3823870e-03,  4.9832854e-03,  4.8945951e-03,  2.9509536e-03,
        1.5311125e-03, -2.6039556e-03,  3.9332011e-03, -1.9741247e-03,
        4.0204180e-03, -3.3078564e-03,  1.8382658e-03, -3.5563370e-04,
       -3.6340037e-03,  1.1658539e-03, -2.0102093e-03,  3.8115149e-03,
        3.9107846e-03, -1.7635567e-03,  8.5493142e-04,  3.0304634e-03,
       -2.5726398e-03, -1.2015039e-03, -2.8207928e-03,  3.5398314e-03,
       -2.2739812e-03,  1.2549283e-03, -4.9413596e-03, -9.1552013e-04,
        3.9929487e-03, -4.6744663e-03,  4.4924277e-03, -1.7868644e-03,
       -2.6038501e-03, -2.1140843e-03, -5.7162246e-04,  2.8567021e-03,
      

## Exercise 2

Train 4 more `Word2vec` models and average the resulting embedding matrices.

In [59]:
corpus_1 = [token.split() for token in tokensss]

word_corpus_1 = Word2Vec(size = 100, window = 5, hs = 0, sample = 0.000001, negative = 5, min_count = 2, iter = 5000, seed=2)

c = word_corpus_1.build_vocab(corpus_1)
d = word_corpus_1.train(corpus_1, total_examples = word_corpus_1.corpus_count, epochs = word_corpus_1.epochs)

In [60]:
w_v_1 = word_corpus_1.wv['have_VERB']

m_s_1 = word_corpus_1.wv.most_similar(['have_VERB'])

w_v_1

array([-2.4693082e-03, -4.8180851e-03,  1.9066523e-04,  1.8176284e-03,
        2.7477841e-03,  4.1055204e-03,  4.3887706e-03,  2.7139205e-03,
        4.7745397e-03, -3.7486930e-03,  1.2037463e-03,  2.0861926e-03,
        1.1613375e-03,  1.2720687e-03, -2.7213539e-03, -7.6296325e-05,
       -1.8362321e-03, -2.3233786e-03,  2.1926444e-03, -4.5521646e-03,
        2.7924187e-03,  4.2836270e-03,  1.0516593e-03,  2.7397925e-03,
       -2.4725404e-03, -1.6038830e-03, -3.2801577e-03, -1.9809124e-03,
       -2.6115908e-03,  3.4528724e-03, -6.7063898e-04, -3.1334576e-03,
        1.1137241e-03,  3.0840742e-03,  8.8552578e-04,  3.8744925e-05,
        3.2428126e-03,  4.7337404e-03, -4.2621088e-03, -2.9215764e-03,
       -2.8982214e-03,  2.2812805e-03,  9.9149346e-04, -4.7208564e-03,
       -9.5363247e-04, -3.1040199e-03,  4.4278065e-03,  3.3265410e-03,
        2.5690815e-03, -1.2308464e-04,  2.9170122e-03,  2.7125007e-03,
       -2.5588043e-03, -4.7134277e-03,  4.7748275e-03,  2.6243818e-03,
      

In [41]:
corpus_2 = [token.split() for token in tokensss]

word_corpus_2 = Word2Vec(size = 100, window = 5, hs = 0, sample = 0.000001, negative = 5, min_count = 2, iter = 5000, seed=3)

e = word_corpus_2.build_vocab(corpus_2)
f = word_corpus_2.train(corpus_2, total_examples = word_corpus_2.corpus_count, epochs = word_corpus_2.epochs)

In [51]:
w_v_2 = word_corpus.wv['have_VERB']

m_s_2 = word_corpus.wv.most_similar(['have_VERB'])

w_v_2

array([-3.4191443e-03,  4.1637928e-03,  4.3452671e-03,  1.1700979e-03,
        1.3707120e-03,  2.7096933e-03, -3.4324133e-03,  3.4854752e-06,
        2.1465884e-03, -2.4696887e-03,  3.7737912e-03, -1.0300397e-03,
       -1.2391248e-03, -4.3925722e-03, -3.4723759e-03,  3.6126757e-03,
        1.6699817e-04, -3.2605417e-04, -2.2566060e-03,  4.3591470e-03,
        1.3823870e-03,  4.9832854e-03,  4.8945951e-03,  2.9509536e-03,
        1.5311125e-03, -2.6039556e-03,  3.9332011e-03, -1.9741247e-03,
        4.0204180e-03, -3.3078564e-03,  1.8382658e-03, -3.5563370e-04,
       -3.6340037e-03,  1.1658539e-03, -2.0102093e-03,  3.8115149e-03,
        3.9107846e-03, -1.7635567e-03,  8.5493142e-04,  3.0304634e-03,
       -2.5726398e-03, -1.2015039e-03, -2.8207928e-03,  3.5398314e-03,
       -2.2739812e-03,  1.2549283e-03, -4.9413596e-03, -9.1552013e-04,
        3.9929487e-03, -4.6744663e-03,  4.4924277e-03, -1.7868644e-03,
       -2.6038501e-03, -2.1140843e-03, -5.7162246e-04,  2.8567021e-03,
      

In [43]:
corpus_3 = [token.split() for token in tokensss]

word_corpus_3 = Word2Vec(size = 100, window = 5, hs = 0, sample = 0.000001, negative = 5, min_count = 2, iter = 5000, seed=4)

g = word_corpus_3.build_vocab(corpus_3)
h = word_corpus_3.train(corpus_3, total_examples = word_corpus_3.corpus_count, epochs = word_corpus_3.epochs)

In [44]:
w_v_3 = word_corpus.wv['have_VERB']

m_s_3 = word_corpus.wv.most_similar(['have_VERB'])

m_s_3

[('pretty_ADV', 0.3252318203449249),
 ('ease_NOUN', 0.2860131561756134),
 ('internet_NOUN', 0.2735349237918854),
 ('one_NUM', 0.26674893498420715),
 ('besides_SCONJ', 0.26259589195251465),
 ('options_NOUN', 0.2562163770198822),
 ('postage_NOUN', 0.25461214780807495),
 ('brand_NOUN', 0.2533974051475525),
 ('friends_NOUN', 0.25308242440223694),
 ('site_NOUN', 0.2435791790485382)]

In [45]:
corpus_4 = [token.split() for token in tokensss]

word_corpus_4 = Word2Vec(size = 100, window = 5, hs = 0, sample = 0.000001, negative = 5, min_count = 2, iter = 5000, seed=5)

i = word_corpus_4.build_vocab(corpus_4)
l = word_corpus_4.train(corpus_4, total_examples = word_corpus_4.corpus_count, epochs = word_corpus_4.epochs)

In [46]:
w_v_4 = word_corpus.wv['have_VERB']

m_s_4 = word_corpus.wv.most_similar(['have_VERB'])

m_s_4

[('pretty_ADV', 0.3252318203449249),
 ('ease_NOUN', 0.2860131561756134),
 ('internet_NOUN', 0.2735349237918854),
 ('one_NUM', 0.26674893498420715),
 ('besides_SCONJ', 0.26259589195251465),
 ('options_NOUN', 0.2562163770198822),
 ('postage_NOUN', 0.25461214780807495),
 ('brand_NOUN', 0.2533974051475525),
 ('friends_NOUN', 0.25308242440223694),
 ('site_NOUN', 0.2435791790485382)]

## Document embeddings with `Doc2Vec`

## Exercise 3

What are the 10 most similar ***words*** to each category?

In [69]:
from gensim.models import Doc2Vec
from gensim.models.doc2vec import TaggedDocument

corpus_n = []

for row in df.iterrows():
    label = row[1].score
    text = row[1].text
    corpus_n.append(TaggedDocument(words=text.split(), 
                                 tags=[str(label)]))

d2v_model = Doc2Vec(vector_size=100, window=10, hs=0, sample=0.000001, negative=7, min_count=3, workers=-1, epochs=500, dm=0)

d2v_model.build_vocab(corpus_n)

d2v_model.train(corpus_n, total_examples=d2v_model.corpus_count, epochs=d2v_model.epochs)


In [76]:
d2v_model.docvecs.doctags

{'5': Doctag(offset=0, word_count=41877, doc_count=802),
 '4': Doctag(offset=1, word_count=6093, doc_count=111),
 '1': Doctag(offset=2, word_count=6665, doc_count=48),
 '2': Doctag(offset=3, word_count=2206, doc_count=17),
 '3': Doctag(offset=4, word_count=2116, doc_count=22)}

In [77]:
target_doc = '2'

similar_docs = d2v_model.docvecs.most_similar(target_doc, topn=4)
print(similar_docs)

[('5', 0.0786687433719635), ('3', 0.06877458095550537), ('4', 0.05270356684923172), ('1', -0.14946088194847107)]
